import Head from "next/head";
import ChooseQuestion from "../components/ChooseQuestion.jsx";
import Link from "next/link.js";

export default function Home() {
  return (
    <div className="h-[100vh] bg-[#FE7280]">
      <Head>
        <title>Quith App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Link href="/quith"></Link>
      <div className="w-[250px] md:w-[500px]  mx-auto h-[100vh] ">
        <ChooseQuestion />
      </div>
    </div>
  );
}
